### ISSUE TITLE
Add Statistics

### ISSUE THREAD

**Issue by samuelechu** [UCSB-CS56-Projects/cs56-pokergame#12]
6ca3ab363cee82335f561fdee85a1472ec89fdae

added Statistics to the start menu

saves the number of times each player has won a game
        -add file to save player statistics if not present
        -handle io file exceptions
        -retrieve records from file and format into a score table

add joptionpane that displays statistics and has button to reset statistics

**Comment by samuelechu** [comment]
estimate : 250 pts

**Comment by mbahia** [comment]
New Estimate 200 pts
