### ISSUE TITLE
Better Playing Screen

### ISSUE THREAD

**Issue by shumarvin** [UCSB-CS56-Projects/cs56-pokergame#15]
Make the main playing screen look better

Some suggestions:
-change background to card playing table
-add sound effects, like the card dealing sound
points: 100pts

**Comment by pconrad** [comment]
Suggestion: next mentor to curate this project, turn this into two issues: a 50 point issue to add the card playing table background,  and a separate 150 point issue to add card dealing sound effect.

**Comment by JohnUCSB** [comment]
F16
