### ISSUE TITLE
Simplify Comparison Code 

### ISSUE THREAD

**Issue by samuelechu** [UCSB-CS56-Projects/cs56-pokergame#9]
Simplifying the hand comparison code with provided Collections methods like Collections.frequency() would result in fewer errors when comparing hands

**Comment by samuelechu** [comment]
bd846c0d7ebfd225c24ac0891012d580a6d3e3db

modified:

isFourOfAKind(), 
isFullHouse(),
isThreeOfAKind(),
isTwoPair(),
isOnePair(),
sameHand(Hand otherHand)

**Comment by shumarvin** [comment]
estimate: 100pts

**Comment by mbahia** [comment]
approved M.B.
